language: cpp
compiler: clang
os: osx
osx_image: xcode12.2
script: cmake -G"Ninja" -B./build -S./llvm-project/llvm -DLLVM_EXTERNAL_PROJECTS="starbytes" -DLLVM_EXTERNAL_STARBYTES_SOURCE_DIR="." -DLLVM_BUILD_TOOLS=OFF -DLLVM_BUILD_UTILS=OFF && cd ./build && cmake --build ./build --parallel


