<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Starbytes Project File Syntax</string>
    <key>scopeName</key>
    <string>source.stbproject</string>
    <key>fileTypes</key>
    <array>
      <string>stbproject</string>
    </array>
    <key>foldingStartMarker</key>
    <string>\:$</string>
    <key>foldingStopMarker</key>
    <string>^\s*(?=module|dump|get|to)</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>name</key>
        <string>strmodule.module</string>
        <key>begin</key>
        <string>\b(module)\b +(\w+)\:$</string>
        <key>end</key>
        <string>^(?=module|dump|get|to)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.strmodule.module</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>support.class</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>module.config-entry</string>
            <key>begin</key>
            <string>^\s*\b(\w+)\b *\:</string>
            <key>end</key>
            <string>^\s*(?=\w+)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.readwrite</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string-literal</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#identifier</string>
              </dict>
              <dict>
                <key>name</key>
                <string>config-entry.array</string>
                <key>begin</key>
                <string>\[</string>
                <key>end</key>
                <string>\]$</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#identifier</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>strmodule.dump</string>
        <key>begin</key>
        <string>\b(dump)\b +(\*|\w+) +\b(to)\b</string>
        <key>end</key>
        <string>^(?=module|dump|get|to)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.strmodule.dump</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.readwrite</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control.strmodule.to</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-literal</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>strmodule.get</string>
        <key>match</key>
        <string>\b(get)\b +(\w+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.strmodule.get</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>support.class</string>
          </dict>
        </dict>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>string-literal</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.strmodule</string>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.strmodule</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <key>identifier</key>
      <dict>
        <key>name</key>
        <string>config-entry.id</string>
        <key>match</key>
        <string>\b(\w+)\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.readwrite</string>
          </dict>
        </dict>
      </dict>
    </dict>
  </dict>
</plist>