<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Starbytes Lang Syntax</string>
    <key>uuid</key>
    <string>86e272a9-6421-4db5-a7b8-01d296c9fca5</string>
    <key>scopeName</key>
    <string>source.stb</string>
    <key>fileTypes</key>
    <array>
      <string>stb</string>
    </array>
    <key>foldingStartMarker</key>
    <string>\{\s*$</string>
    <key>foldingStopMarker</key>
    <string>^\s*\}</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#statements</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>statements</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#declarations</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>declarations</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#variable-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#import-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#scope-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#class-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#if-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#single-comment</string>
          </dict>
        </array>
      </dict>
      <key>expressions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#literals</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#call-expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#boolean</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#single-comment</string>
          </dict>
        </array>
      </dict>
      <key>single-comment</key>
      <dict>
        <key>name</key>
        <string>comment.line.double-slash</string>
        <key>match</key>
        <string>\/\/.*</string>
      </dict>
      <key>number</key>
      <dict>
        <key>name</key>
        <string>constant.numeric</string>
        <key>match</key>
        <string>[0-9]+(?:\.[0-9]+)?</string>
      </dict>
      <key>boolean</key>
      <dict>
        <key>name</key>
        <string>constant.language</string>
        <key>match</key>
        <string>(?:true|false)</string>
      </dict>
      <key>identifier</key>
      <dict>
        <key>name</key>
        <string>variable.readwrite.strbyts</string>
        <key>match</key>
        <string>\b\w+\b</string>
      </dict>
      <key>call-expression</key>
      <dict>
        <key>name</key>
        <string>strbyts.callexp</string>
        <key>begin</key>
        <string>(\w+)\s*\(</string>
        <key>end</key>
        <string>\s*\)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
        </array>
      </dict>
      <key>literals</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-literal</string>
          </dict>
        </array>
      </dict>
      <key>string-literal</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.strbyts</string>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.strbyts</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <key>import-declaration</key>
      <dict>
        <key>name</key>
        <string>strbyts.import</string>
        <key>match</key>
        <string>\b(import)\b +(\w+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.strbyts.import</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.readwrite</string>
          </dict>
        </dict>
      </dict>
      <key>scope-declaration</key>
      <dict>
        <key>name</key>
        <string>strbyts.scope</string>
        <key>begin</key>
        <string>\b(scope)\b +(\w+)\s*\{</string>
        <key>end</key>
        <string>^\s*\}</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.strbyts.scope</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.readwrite</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#statements</string>
          </dict>
        </array>
      </dict>
      <key>variable-declaration</key>
      <dict>
        <key>name</key>
        <string>strbyts.decl</string>
        <key>match</key>
        <string>\b(decl)\b +(\w+):?(\w+)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.strbyts.decl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.readwrite</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type</string>
          </dict>
        </dict>
      </dict>
      <key>function-declaration</key>
      <dict>
        <key>name</key>
        <string>strbyts.func</string>
        <key>begin</key>
        <string>\b(func)\b +(\w+) *</string>
        <key>end</key>
        <string>(?&lt;=\})</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.strbyts.func</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#function-params</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-return</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-body</string>
          </dict>
        </array>
      </dict>
      <key>if-declaration</key>
      <dict>
        <key>name</key>
        <string>strbyts.if</string>
        <key>begin</key>
        <string>\b(if)\b *</string>
        <key>end</key>
        <string>(?&lt;=\})</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.strbyts.if</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#if-decl-paren</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block-statement</string>
          </dict>
        </array>
      </dict>
      <key>if-decl-paren</key>
      <dict>
        <key>name</key>
        <string>strbyts.if.parens</string>
        <key>begin</key>
        <string>\(</string>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>block-statement</key>
      <dict>
        <key>name</key>
        <string>strbyts.block</string>
        <key>begin</key>
        <string>\{</string>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#throw-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#return-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#statements</string>
          </dict>
        </array>
      </dict>
      <key>typedParameter</key>
      <dict>
        <key>name</key>
        <string>strbyts.tparam</string>
        <key>match</key>
        <string>(\w+):(\w+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.parameter</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type</string>
          </dict>
        </dict>
      </dict>
      <key>function-params</key>
      <dict>
        <key>name</key>
        <string>strbyts.func.params</string>
        <key>begin</key>
        <string>\(</string>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#typedParameter</string>
          </dict>
        </array>
      </dict>
      <key>return-declaration</key>
      <dict>
        <key>name</key>
        <string>strbyts.func.body.return-decl</string>
        <key>begin</key>
        <string>\b(return)\b +</string>
        <key>end</key>
        <string>(?&lt;=\})|(?=(?:decl|class|func|scope|import|if|else|switch|case|loose|immutable|alias|deftype|return|secure|throw))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.strbyts.return</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>throw-declaration</key>
      <dict>
        <key>name</key>
        <string>strbyts.func.body.throw-decl</string>
        <key>begin</key>
        <string>\b(throw)\b +</string>
        <key>end</key>
        <string>(?&lt;=\})|(?=(?:decl|class|func|scope|import|if|else|switch|case|loose|immutable|alias|deftype|return|secure|throw))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.strbyts.throw</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expressions</string>
          </dict>
        </array>
      </dict>
      <key>function-body</key>
      <dict>
        <key>name</key>
        <string>strbyts.func.body</string>
        <key>begin</key>
        <string>\{</string>
        <key>end</key>
        <string>^\s*\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#throw-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#return-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#statements</string>
          </dict>
        </array>
      </dict>
      <key>function-return</key>
      <dict>
        <key>name</key>
        <string>strbys.func.return</string>
        <key>match</key>
        <string>&gt;[?!&gt;] *(\w+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.type</string>
          </dict>
        </dict>
      </dict>
      <key>class-declaration</key>
      <dict>
        <key>name</key>
        <string>strbyts.class</string>
        <key>begin</key>
        <string>\b(class)\b *\b(\w+)\b\s*\{</string>
        <key>end</key>
        <string>^\s*\}</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.strbyts.class</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.class</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#class-body-declarations</string>
          </dict>
        </array>
      </dict>
      <key>class-body-declarations</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#class-property-declaration</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#class-method-declaration</string>
          </dict>
        </array>
      </dict>
      <key>class-property-declaration</key>
      <dict>
        <key>name</key>
        <string>strbyts.class.property</string>
        <key>match</key>
        <string>^\s*(immutable)? +(loose)? +\b(\w+)\b(?! *\()</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.strbyts.immutable</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.strbyts.loose</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.readwrite</string>
          </dict>
        </dict>
      </dict>
      <key>class-method-declaration</key>
      <dict>
        <key>name</key>
        <string>strbyts.class.function</string>
        <key>begin</key>
        <string>^\s*\b(\w+)\b *</string>
        <key>end</key>
        <string>(?&lt;=\})</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#function-params</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-return</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-body</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>